## YAML Template.
---
presets:
    filterSets:
        -
            name: 'All'
            filter: 'Class != 12000'
        -
            name: 'All service'
            filter: 'Class = 12000'
        -
            name: 'All ITNM'
            filter: 'Class = 8000 and Severity !=0'
        -
            name: 'Trap'
            filter: 'Class = 300 or Class >= 40000'
        -
            name: 'Last 10 min'
            filter: 'Class not in (12000,99999) and Severity != 0 and LastOccurrence > getdate() - 600'
        -
            name: 'Critical'
            filter: 'Class != 12000 and Severity = 5'
        -
            name: 'Major'
            filter: 'Class != 12000 and Severity = 4'
        -
            name: 'Minor'
            filter: 'Class != 12000 and Severity = 3'
        -
            name: 'Warning'
            filter: 'Class != 12000 and Severity = 2'
        -
            name: 'Unknown'
            filter: 'Class != 12000 and Severity = 1'
        -
            name: 'Clear'
            filter: 'Class != 12000 and Severity = 0'
---
columns:
    colSets:
        -
            col: 'summary'
            header: 'Summary'
        -
            col: 'eventId'
            header: 'EventId'
        -
            col: 'expireTime'
            header: 'ExpireTime'
        -
            col: 'tally'
            header: 'Count'

#    colDetails:
#      - itmApplLabel
#      - radServiceName
---
colors:
    colorSets:
        -
            code: 0
            color: 'LimeGreen'
        -
            code: 1
            color: 'MediumOrchid'
        -
            code: 2
            color: 'SkyBlue'
        -
            code: 3
            color: 'yellow'
        -
            code: 4
            color: 'orange'
        -
            code: 5
            color: 'Red'